spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/db?retryWrites=true&w=majority
  cloud:
    config:
      enabled: false

aws:
  access_key_id: <SEU_ACCESS_KEY_ID>
  secret_access_key: <SEU_SECRET_KEY>

s3:
  bucket: <SEU_BUCKET>
  region: <SEU_REGION>

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

